name: Create or Update Repo

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: "Name of the repo to create"
        required: true
        type: string
      package_import_name:
        description: "Used in imports e.g. from <name> import ..."
        required: true
        type: string
      is_public:
        description: "If unchecked, repo is private"
        required: false
        default: false
        type: boolean
      protect_main:
        description: "Requires GitHub Pro for private repos."
        required: false
        default: false
        type: boolean


env:
  GH_TOKEN: ${{ secrets.PERSONAL_GH_TOKEN }}

jobs:
  create-repo-if-not-exists:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "Run create repo script"
        env:
          REPO_NAME: ${{ github.event.inputs.repo_name }}
          GITHUB_USERNAME: eric-adam-garner
          IS_PUBLIC: ${{ github.event.inputs.is_public }}
        run: |
          bash run.sh create-repo-if-not-exists

  configure-repo:
    needs: [create-repo-if-not-exists]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Run configure-repo script"
        env:
          REPO_NAME: ${{ github.event.inputs.repo_name }}
          GITHUB_USERNAME: eric-adam-garner
          TEST_PYPI_TOKEN: ${{ secrets.TEST_PYPI_TOKEN }}
          PROD_PYPI_TOKEN: ${{ secrets.PROD_PYPI_TOKEN }}
          PROTECT_MAIN: ${{ github.event.inputs.protect_main }}
        run: |
          bash run.sh configure-repo

  open-pr-with-generated-project:
    needs: [create-repo-if-not-exists]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: "Run open-pr-with-generated-project script"
        env:
          REPO_NAME: ${{ github.event.inputs.repo_name }}
          PACKAGE_IMPORT_NAME: ${{ github.event.inputs.package_import_name }}
          GITHUB_USERNAME: eric-adam-garner
          AUTHOR: "Eric Adam Garner"
          AUTHOR_EMAIL: eric.adam.garner@gmail.com
        run: |
          bash run.sh open-pr-with-generated-project
